### PR TITLE
Support Ed25519 public/private key generation

### PR DESCRIPTION
**Pull request by kaidence**
Hi! I've been looking to generate Ed25519 keys through Terraform. Unfortunately, this was missing from the official TLS provider. I took a stab at adding support for this. The changes are:

1. Updates the vendored golang.org/x/crypto
2. Adds support for Ed25519 in resource_private_key.go, relying on golang.org/x/crypto/ed25519 

I'd love for someone to take a look and see whether this is something that could be included in the mainline terraform-provider-tls repository.

### CODE REVIEW

**Comment by kaidence** [comment]
The CI fails since the upgraded golang.org/x/crypto package relies on Go 1.9 or higher. Would there be interest in upgrading the required Go version for this project too?

**Comment by adamdecaf** [comment]
@kaidence I created https://github.com/terraform-providers/terraform-provider-tls/pull/33 and PR'd the template project too.

**Comment by kaidence** [comment]
@adamdecaf Wonderful, thank you so much!

**Comment by kaidence** [comment]
Closing this while I get permission from my employer, will reopen once I get that

**Comment by detro** [comment]
Thank you for your time and contribution, we really appreciate it. As part of a bigger effort to add complete support for ED25519 key algorithm, I’m closing this in favor of issue [#150](https://github.com/hashicorp/terraform-provider-tls/issues/150). Please refer to the new issue for what will be included and how work will proceed.

**Pull request closed without merging**
