### PR TITLE
Fix crash when subject block is empty

### PR DESCRIPTION
**Pull request by SpencerBrown**
Fixes issue #1 (panic when subject block is empty in tls_cert_request). Return error instead. Same panic occurs in tls_self_signed_cert, fixed that also.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks for fixing this, @SpencerBrown!

The change looks good. I noticed there's some commented-out code in the test. Is that due to the change in certificate? Do you know what it'd take to be able to un-comment that again?

**Comment by SpencerBrown** [comment]
Thanks for reviewing this PR! Yes, this is due to the change in certificate. I used this provider to generate a new hard-coded CA certificate and private key in `tls/provider_test.go`, because the old one had expired causing the test to fail. This provider is not able to set the AuthorityKeyID field, thus I commented out the test for it. 

To enable this test, I would need to either:

1. Generate the hard-coded test CA cert and private key by other means (e.g. OpenSSL), and include the AuthorityKeyID
2. Add the ability to set the AuthorityKeyID to this provider, then use it to generate the hard-coded test CA certificate and private key

Option (1) does not seem to progress the cause of this provider. Adding this test back in would not be testing anything that this provider currently handles. 

Option (2) seems reasonable to me, but would be better handled by a separate PR implementing the AuthorityKeyID feature, then adding back the test for it. I would be happy to do this as time allows, as it would advance the capabilities of this provider.

What do you think?

**Comment by apparentlymart** [comment]
Thanks for that additional context, @SpencerBrown!

Given what you explained here, I'm happy to move forward with this code removed altogether and then we can potentially add this back in a later change that also adds support for the feature. 

Would you mind updating this to remove that commented-out code (just so it isn't confusing to any future maintainer looking at this code)? I think this is ready to go after that, and we can always find that old code in the version control history if we want to re-introduce it later.

Thanks again for working on this!

**Comment by SpencerBrown** [comment]
Thanks! I removed the commented-out code.

**Comment by apparentlymart** [comment]
Thanks @SpencerBrown!

**Pull request merged**
